FROM python:3.5
ENV PYTHONBUFFERED 1

RUN apt-get update
RUN curl -sL https://deb.nodesource.com/setup_5.x > node.sh
RUN bash /node.sh
RUN apt-get install -y nodejs

COPY ./requirements /requirements
RUN pip install -r /requirements/local.txt

COPY ./compose/django/entrypoint.sh /entrypoint.sh
RUN sed -i 's/\r//' /entrypoint.sh
RUN chmod +x /entrypoint.sh

WORKDIR /app

ENTRYPOINT ["/entrypoint.sh"]
