# -*- coding: utf-8 -*-
# Generated by Django 1.9c2 on 2015-11-30 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='position_line',
            field=models.CharField(blank=True, choices=[('GK', 'Goalkeepers'), ('DEF', 'Defenders'), ('MID', 'Midfielders'), ('ATT', 'Attackers')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(blank=True, choices=[('GK', 'GK'), ('RWB', 'RWB'), ('RB', 'RB'), ('CB', 'CB'), ('LB', 'LB'), ('LWB', 'LWB'), ('CDM', 'CDM'), ('CM', 'CM'), ('CAM', 'CAM'), ('RM', 'RM'), ('RW', 'RW'), ('RF', 'RF'), ('LM', 'LM'), ('LW', 'LW'), ('LF', 'LF'), ('CF', 'CF'), ('ST', 'ST')], max_length=3, null=True),
        ),
    ]
