# -*- coding: utf-8 -*-
# Generated by Django 1.9c2 on 2015-11-30 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_auto_20151130_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='is_gk',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='is_loan',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='is_special_type',
            field=models.NullBooleanField(default=False),
        ),
    ]
