# -*- coding: utf-8 -*-
# Generated by Django 1.9c2 on 2015-11-30 22:07
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_auto_20151130_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='specialities',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='traits',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
