# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-28 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_auto_20160319_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='cached_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
