# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-28 15:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0006_player_cached_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='ballcontrol',
            new_name='ball_control',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='freekickaccuracy',
            new_name='free_kick_accuracy',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='gkdiving',
            new_name='gk_diving',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='gkhandling',
            new_name='gk_handling',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='gkkicking',
            new_name='gk_kicking',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='gkpositioning',
            new_name='gk_positioning',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='gkreflexes',
            new_name='gk_reflexes',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='headingaccuracy',
            new_name='heading_accuracy',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='longpassing',
            new_name='long_passing',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='longshots',
            new_name='long_shots',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='shortpassing',
            new_name='short_passing',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='shotpower',
            new_name='shot_power',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='slidingtackle',
            new_name='sliding_tackle',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='sprintspeed',
            new_name='sprint_speed',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='standingtackle',
            new_name='standing_tackle',
        ),
    ]
