# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-24 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0007_auto_20160328_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='color',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='quality',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
