# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 16:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0009_auto_20160501_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='age',
        ),
    ]
